package com.softserve.edu04;

import com.softserve.hw03.InputReader;
import java.io.IOException;

public enum Country {
    _001("Algeria", "Africa"),
    _002("Angola", "Africa"),
    _003("Benin", "Africa"),
    _004("Botswana", "Africa"),
    _005("Burkina Faso", "Africa"),
    _006("Burundi", "Africa"),
    _007("Cameroon", "Africa"),
    _008("Cape Verde", "Africa"),
    _009("Central African Republic", "Africa"),
    _010("Chad", "Africa"),
    _011("Comoros", "Africa"),
    _012("Republic of the Congo", "Africa"),
    _013("Democratic Republic of the Congo", "Africa"),
    _014("Côte d'Ivoire", "Africa"),
    _015("Djibouti", "Africa"),
    _016("Equatorial Guinea", "Africa"),
    _017("Egypt", "Africa"),
    _018("Eritrea", "Africa"),
    _019("Ethiopia", "Africa"),
    _020("Gabon", "Africa"),
    _021("The Gambia", "Africa"),
    _022("Ghana", "Africa"),
    _023("Guinea", "Africa"),
    _024("Guinea-Bissau", "Africa"),
    _025("Kenya", "Africa"),
    _026("Lesotho", "Africa"),
    _027("Liberia", "Africa"),
    _028("Libya", "Africa"),
    _029("Madagascar", "Africa"),
    _030("Malawi", "Africa"),
    _031("Mali", "Africa"),
    _032("Mauritania", "Africa"),
    _033("Mauritius", "Africa"),
    _034("Morocco", "Africa"),
    _035("Mozambique", "Africa"),
    _036("Namibia", "Africa"),
    _037("Niger", "Africa"),
    _038("Nigeria", "Africa"),
    _039("Réunion", "Africa"),
    _040("Rwanda", "Africa"),
    _041("São Tomé and Príncipe", "Africa"),
    _042("Senegal", "Africa"),
    _043("Seychelles", "Africa"),
    _044("Sierra Leone", "Africa"),
    _045("Somalia", "Africa"),
    _046("South Africa", "Africa"),
    _047("South Sudan", "Africa"),
    _048("Sudan", "Africa"),
    _049("Swaziland", "Africa"),
    _050("Tanzania", "Africa"),
    _051("Togo", "Africa"),
    _052("Tunisia", "Africa"),
    _053("Uganda", "Africa"),
    _054("Western Sahara", "Africa"),
    _055("Zambia", "Africa"),
    _056("Zimbabwe", "Africa"),
    _057("Afghanistan", "Asia"),
    _058("Armenia", "Asia"),
    _059("Azerbaijan", "Asia"),
    _060("Bahrain", "Asia"),
    _061("Bangladesh", "Asia"),
    _062("Bhutan", "Asia"),
    _063("Brunei", "Asia"),
    _064("Cambodia", "Asia"),
    _065("China", "Asia"),
    _066("East Timor", "Asia"),
    _067("Georgia", "Asia"),
    _068("India", "Asia"),
    _069("Indonesia", "Asia"),
    _070("Iran", "Asia"),
    _071("Iraq", "Asia"),
    _072("Israel", "Asia"),
    _073("Japan", "Asia"),
    _074("Jordan", "Asia"),
    _075("Kazakhstan", "Asia"),
    _076("Kuwait", "Asia"),
    _077("Kyrgyzstan", "Asia"),
    _078("Laos", "Asia"),
    _079("Lebanon", "Asia"),
    _080("Malaysia", "Asia"),
    _081("The Maldives", "Asia"),
    _082("Mongolia", "Asia"),
    _083("Myanmar", "Asia"),
    _084("Nepal", "Asia"),
    _085("North Korea", "Asia"),
    _086("Oman", "Asia"),
    _087("Pakistan", "Asia"),
    _088("Palestine", "Asia"),
    _089("The Philippines", "Asia"),
    _090("Qatar", "Asia"),
    _091("Russia", "Asia"),
    _092("Saudi Arabia", "Asia"),
    _093("Singapore", "Asia"),
    _094("South Korea", "Asia"),
    _095("Sri Lanka", "Asia"),
    _096("Syria", "Asia"),
    _097("Tajikistan", "Asia"),
    _098("Thailand", "Asia"),
    _099("Turkey", "Asia"),
    _100("Turkmenistan", "Asia"),
    _101("United Arab Emirates", "Asia"),
    _102("Uzbekistan", "Asia"),
    _103("Vietnam", "Asia"),
    _104("Yemen", "Asia"),
    _105("Albania", "Europe"),
    _106("Andorra", "Europe"),
    _107("Austria", "Europe"),
    _108("Belarus", "Europe"),
    _109("Belgium", "Europe"),
    _110("Bosnia and Herzegovina", "Europe"),
    _111("Bulgaria", "Europe"),
    _112("Croatia", "Europe"),
    _113("Cyprus", "Europe"),
    _114("Czech Republic", "Europe"),
    _115("Denmark", "Europe"),
    _116("Estonia", "Europe"),
    _117("Finland", "Europe"),
    _118("France", "Europe"),
    _119("Georgia", "Europe"),
    _120("Germany", "Europe"),
    _121("Greece", "Europe"),
    _122("Hungary", "Europe"),
    _123("Iceland", "Europe"),
    _124("Ireland", "Europe"),
    _125("Italy", "Europe"),
    _126("Kosovo", "Europe"),
    _127("Latvia", "Europe"),
    _128("Liechtenstein", "Europe"),
    _129("Lithuania", "Europe"),
    _130("Luxembourg", "Europe"),
    _131("North Macedonia", "Europe"),
    _132("Malta", "Europe"),
    _133("Moldova", "Europe"),
    _134("Monaco", "Europe"),
    _135("Montenegro", "Europe"),
    _136("Netherlands", "Europe"),
    _137("Norway", "Europe"),
    _138("Poland", "Europe"),
    _139("Portugal", "Europe"),
    _140("Romania", "Europe"),
    _141("Russia", "Europe"),
    _142("San Marino", "Europe"),
    _143("Serbia", "Europe"),
    _144("Slovakia", "Europe"),
    _145("Slovenia", "Europe"),
    _146("Spain", "Europe"),
    _147("Sweden", "Europe"),
    _148("Switzerland", "Europe"),
    _149("Turkey", "Europe"),
    _150("Ukraine", "Europe"),
    _151("United Kingdom", "Europe"),
    _152("Vatican", "Europe"),
    _153("Canada", "North America"),
    _154("Mexico", "North America"),
    _155("USA", "North America"),
    _156("Navassa Island", "North America"),
    _157("Puerto Rico", "North America"),
    _158("US Virgin Islands", "North America"),
    _159("Dominican Republic", "North America"),
    _160("Cuba", "North America"),
    _161("Haiti", "North America"),
    _162("Belize", "North America"),
    _163("Costa Rica", "North America"),
    _164("El Salvador", "North America"),
    _165("Guatemala", "North America"),
    _166("Honduras", "North America"),
    _167("Guadeloupe", "North America"),
    _168("Martinique", "North America"),
    _169("Nicaragua", "North America"),
    _170("Panama", "North America"),
    _171("Jamaica", "North America"),
    _172("Bahamas", "North America"),
    _173("Barbados", "North America"),
    _174("Dominica", "North America"),
    _175("Brazil", "South America"),
    _176("Argentina", "South America"),
    _177("Bolivia", "South America"),
    _178("Chile", "South America"),
    _179("Colombia", "South America"),
    _180("Ecuador", "South America"),
    _181("Falkland Islands", "South America"),
    _182("French Guiana", "South America"),
    _183("Guyana", "South America"),
    _184("Paraguay", "South America"),
    _185("Peru", "South America"),
    _186("South Georgia and the South Sandwich Islands", "South America"),
    _187("Suriname", "South America"),
    _188("Trinidad and Tobago", "South America"),
    _189("Uruguay", "South America"),
    _190("Venezuela", "South America"),
    _191("Australia", "Oceania"),
    _192("Fiji", "Oceania"),
    _193("New Zealand", "Oceania"),
    _194("Federated States of Micronesia", "Oceania"),
    _195("Kiribati", "Oceania"),
    _196("Marshall Islands", "Oceania"),
    _197("Nauru", "Oceania"),
    _198("Palau", "Oceania"),
    _199("Papua New Guinea", "Oceania"),
    _200("Samoa", "Oceania"),
    _201("Solomon Islands", "Oceania"),
    _202("Tonga", "Oceania"),
    _203("Tuvalu", "Oceania"),
    _204("Vanuatu", "Oceania");

    private final String country;
    private final String continent;

    Country(String country, String continent) {
        this.country = country;
        this.continent = continent;
    }

    public String getCountry() {
        return country;
    }

    public String getContinent() {
        return continent;
    }

    public static void getCountryInfo() throws IOException {
        String countryInput;
        System.out.print("\nEnter counry: ");
        countryInput = InputReader.getInputString();

        for (Country i : values()) {
            if (i.country.equals(countryInput))
                System.out.println("Country " + i.country
                        + " placed on " + i.continent + " continent.");
        }
    }
}
